### PR TITLE
fix cases of composed line where datapoint is not initialized

### PR DESCRIPTION
**Pull request by mizrachiran**
This small change fix bug #16 (multiple vcards import cause an error).
Was verified carefully with multiple sets of vcards. all UTs pass.

### CODE REVIEW

**Comment by clochix** [comment]
Thanks a lot @mizrachiran ! @jacquarg or @aenario, could you have a look at this please ?

**Comment by frankrousseau** [comment]
@mizrachiran Could you add tests?

**Comment by mizrachiran** [comment]
Hi @frankrousseau,

I added a test, it doesn't check much but it will function as a gate to ensure this functionality.

**Comment by mizrachiran** [comment]
I would appreciate if you will release an update to the npm package once you merge this change.

Thanks!

**Comment by frankrousseau** [comment]
Great thank you!

**Comment by frankrousseau** [comment]
Published as 0.2.14

**Pull request merged**
