### PR TITLE
Added support for TZ, LANG, GEO, GENDER, KIND

### PR DESCRIPTION
**Pull request by nehakadam**
Following fields can be parsed from and exported to vCard format -

1. TZ
2. LANG (Simple, without PREF)
3. GEO
4. GENDER
5. KIND

### CODE REVIEW

**Comment by frankrousseau** [comment]
Great, thank you @nehakadam. Can you add tests for this new fields?

**Comment by nehakadam** [comment]
@frankrousseau Added tests for new fields.

**Comment by frankrousseau** [comment]
Great! Thank you @nehakadam

**Comment by frankrousseau** [comment]
Changes published as a 0.2.16 version.

**Pull request merged**
