### PR TITLE
Support multiple cases for the x-socialprofile field

### PR DESCRIPTION
**Pull request by mizrachiran**
Support multiple cases, observed on iOS, for the x-socialprofile field.
In the previous implementation, when the charset is presented I was getting type=utf & value=facebook.
This implementation support both types.

The following variations were checked:
X-SOCIALPROFILE;type=facebook;x-user=lee.nadel;x-userid=807274769;x-displayname=Lee Nadel:http://www.facebook.com/lee.nadel
X-SOCIALPROFILE;CHARSET=UTF-8;TYPE=facebook:barak.bukshpan
X-SOCIALPROFILE;TYPE=facebook:barak.bukshpan

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hi @mizrachiran,

  Thank you for the fix. Can you add a test for your use case?

**Comment by mizrachiran** [comment]
I added unittest to validate the 3 different cases I observed.
Let me know if anything else is needed.

Thanks!

**Comment by frankrousseau** [comment]
Awesmone. Thank you!

**Comment by frankrousseau** [comment]
Published as 0.2.13

**Pull request merged**
