### PR TITLE
Serialize cozy tags in vCard CATEGORIES field (and parse)

### PR DESCRIPTION
**Pull request by jacquarg**
- Serialize cozy tags in vCard CATEGORIES field (and parse)
- skip non vCard BEGIN .. END blocks (as VList from SOGo thunderbird addon).
- add tests for SOGo, DavDroid, ...

### CODE REVIEW

**Comment by hansbkk** [comment]
Does this leave existing category (often used as 'group' in external apps) data in place undisturbed?

New Cozy tags should just be added, not replacing existing user data as originally imported.

FFR to incoming googlers: more general issue here: cozy/cozy-sync#26

----------------
Also hopefully (to be) included in the ". . ." IMO should be 

CardDAV-Sync http://dmfs.org/carddav/
ContactSync http://ntbab.dyndns.org/apache2-default/seite/contactsync.html

These usually test well against Baïkal, Radicale and SabreDAV (covers others including OwnCloud)

please ignore all this if inappropriate, non-dev noob user only. . .

**Comment by aenario** [comment]
Thanks @jacquarg for the PR

Thanks @hansbkk for your feedback, always apreciated : 
"Does this leave existing category (often used as 'group' in external apps) data in place undisturbed?"
Yes, they will be added as tags in cozy, and stay unless the user delete them manually from the web interface.

CardDAV-Sync is the client we used and mimic for our initial Android test-suite in cozy-sync (https://github.com/cozy/cozy-sync/blob/master/tests/carddav.coffee)

Didn't know about ContactSync, will look into it.

**Comment by aenario** [comment]
Published as v0.2.1

**Comment by hansbkk** [comment]
@aenario ContactSync is the bee's knees, like vdirsyncer in that it will preserve full fidelity of vCards, allows a remote VCF (single-file only) to act as the other side of a CardDAV sync, very flexible and so far bullet-proof reliable. The author "Annemarie Böhmer"<consync@gmx.at> is very approachable and helpful.

**Pull request merged**
